os: unstable

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: |
     New-Item -ItemType Directory -Force -Path C:\build
     $source = "https://developer.spotify.com/download/libspotify/libspotify-12.1.51-win32-release.zip"
     $destination = "C:\build\libspotify-win32.zip"
     Invoke-WebRequest $source -OutFile $destination
     Expand-Archive C:\build\libspotify-win32.zip -DestinationPath C:\build\libspotify
     Install-Product node $env:nodejs_version x86
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm run lint
  - npm run test
  - npm run build
  - npm run test-e2e
  - npm run package
